# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.20.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
my_array = np.zeros((10))
memory = np.size(my_array)*my_array.itemsize
memory

80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [168]:
# help(np.add)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
my_array = np.zeros((10))
my_array[4] = 5
my_array

array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [8]:
my_vector = np.arange(10)
reversed_vector = my_vector[::-1]
reversed_vector

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [11]:
my_array = np.asarray([1, 2, 0, 0, 4, 0])
np.where(my_array == 0)

(array([2, 3, 5], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
np.random.random(size = (3,3,3))

array([[[0.58785218, 0.12099099, 0.89548823],
        [0.30351285, 0.88481792, 0.7718669 ],
        [0.77041022, 0.61987686, 0.96504439]],

       [[0.88452844, 0.51404824, 0.91139352],
        [0.25998917, 0.80273933, 0.59994244],
        [0.65736315, 0.80746724, 0.84525014]],

       [[0.36609035, 0.10026979, 0.44468173],
        [0.07414077, 0.61540287, 0.59945002],
        [0.36547203, 0.91357102, 0.12531022]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
my_array = np.random.randint(0, 100,  size = (10, 10))
print("Maximum: ", np.max(my_array))
print("Minimum: ", np.min(my_array))

Maximum:  99
Minimum:  1


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
my_array = np.random.rand(30)
my_array.mean()

0.5242515218478602

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
my_array = np.ones((5,5))
my_array[1:-1, 1:-1] = 0
my_array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
a = np.zeros((10,10))
np.pad(a, (1,1), 'constant', constant_values = (1,1))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [26]:
print(0* np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [32]:
np.diag([1,2,3,4], k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [35]:
# pattern = np.zeros((8,8))
# pattern[::2 , 1::2] = 1
# pattern[1::2, ::2] = 1
# pattern

# row, col = np.indices(8,8)
i,j = np.indices((8,8))
M = ( 1- ((-1)**(i+j)) )/2
M

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [34]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [231]:
pattern = np.asarray([[0, 1], 
                    [1, 0]])
np.tile(pattern, (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [42]:
my_array = np.arange(25).reshape(5, 5)
print("Original array:\n", my_array)

norm_array = (my_array - my_array.min())/(my_array.max() - my_array.min())
print("\nNormalized array with min-max:\n", norm_array)

Original array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Normalized array with min-max:
 [[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [48]:
# for color in [R, G, B]:
#     color = np.arange(0, 255, dtype = "unint8")

# A = np.arange()
# help(np.dtype)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [74]:
A = np.random.randint(0,10, size = (5,3))
B = np.random.randint(0,10, size = (3,2))
print("A:\n", A)
print("\nB:\n", B)
print("\nA*B:\n", np.dot(A, B))

A:
 [[1 7 8]
 [2 0 6]
 [1 9 9]
 [4 8 1]
 [3 8 8]]

B:
 [[1 6]
 [3 0]
 [4 7]]

A*B:
 [[54 62]
 [26 54]
 [64 69]
 [32 31]
 [59 74]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [89]:
my_array = np.random.randint(-9,10, size = 10)
print("Original: ", my_array)
my_array[(my_array > 3) & (my_array < 8)] *= -1
print("Negated: ", my_array)

Original:  [ 4  0  3  7 -2  3 -4 -9  1  3]
Negated:  [-4  0  3 -7 -2  3 -4 -9  1  3]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [90]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [141]:
Z = np.arange(0,10, 2)
print(Z)
# Z**Z
print(2 << Z >> 2)   # << and >> are bit shift operators 
                # x << Z --> x = x*2^Z or x = x*2^Z, here x is 2, that results in
                # [  2,   8,  32, 128, 512]
                # result >> Z --> result = result//2^Z
print(Z <- Z)        # equivalent to <(-Z)
print(1j*Z)     # Conversts to complex numbers with Z as imaginary part
print(Z/1/1)    # consecutive division  
Z <Z> Z         # Invalid operation

[0 2 4 6 8]
[  0   2   8  32 128]
[False False False False False]
[0.+0.j 0.+2.j 0.+4.j 0.+6.j 0.+8.j]
[0. 2. 4. 6. 8.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [155]:
print("First line: ", np.array(0) / np.array(0))
print("Middle line: ", np.array(0) // np.array(0))
print("Last line: ", np.array([np.nan]).astype(int).astype(float))

First line:  nan
Middle line:  0
Last line:  [-2.14748365e+09]
<ipython-input-155-caaf0f792cb9>:1: RuntimeWarning: invalid value encountered in true_divide
  print("First line: ", np.array(0) / np.array(0))
<ipython-input-155-caaf0f792cb9>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print("Middle line: ", np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [177]:
M = np.random.uniform(-5, 5, size = (3,3))
print("Original array:\n", M)

N = np.ceil(np.abs(M))
N[(M < 0)] *= -1
print("\nRounded away from 0:\n", N)

Original array:
 [[ 4.86486965  4.41588956  3.35852918]
 [ 3.90005326 -3.58390073  3.71458379]
 [ 1.41675835  2.9157127   0.40081428]]

Rounded away from 0:
 [[ 5.  5.  4.]
 [ 4. -4.  4.]
 [ 2.  3.  1.]]


#### 30. How to find common values between two arrays? (★☆☆)

In [185]:
A = np.arange(0,15).reshape(5,3)
B = np.arange(5,14).reshape(3,3)
print("A:\n", A)
print("\nB:\n", B)
np.intersect1d(A,B)

A:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

B:
 [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [202]:
# np.seterr(all="ignore") 
# Z = np.ones(1) / 0

# np.seterr(over = 'warn', divide = 'warn', invalid = 'warn', under = 'ignore')
# Z = np.ones(1) / 0

<ipython-input-202-dcf67b5abc36>:5: RuntimeWarning: divide by zero encountered in true_divide
  Z = np.ones(1) / 0


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [203]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False
<ipython-input-203-c6ff0ad7fd7b>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [111]:
year_calendar = np.datetime64('2016')


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [132]:
my_dates = np.arange('2016-07', '2016-08', dtype = 'datetime64[D]')
my_dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [143]:
A = np.asarray([1, 2])
B = np.asarray([2, 1])
print("Should be False:", np.array_equal(A,B))
# Reversing A so that they are equal
print("Should be True:", np.array_equal(A[::-1], B))

Should be False: False
Should be True: True


#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [160]:
my_array = np.random.randint(1,10, size = (5,5))

print("Before swapping:\n ", my_array)
my_array[[0,3]] = my_array[[3,0]]
print("After swapping row 1 and row 4:\n ", my_array)

Before swapping:
  [[3 9 3 8 1]
 [2 7 1 5 9]
 [3 8 8 5 2]
 [3 2 2 1 5]
 [9 1 5 7 9]]
After swapping row 1 and row 4:
  [[3 2 2 1 5]
 [2 7 1 5 9]
 [3 8 8 5 2]
 [3 9 3 8 1]
 [9 1 5 7 9]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [175]:
def moving_average(arr, window):
    """
    Inputs: 
    arr: 1D or 2D array
    window: window size over which to average
    Returns:
    Array with the averages
    """
    rows = arr.shape[0] - (window.shape[0] - 1)
    columns = arr.shape[1] - (window.shape[1] - 1)
    averages = np.zeros((rows, columns))

    for i in range(rows):
        for j in range(columns):
            averages[i, j] = np.mean(arr[i:i+1, j, j+1])/(rows*columns)
            
    return averages    

main_array = np.arange(1,10)
window = np.asarray([2,2])
print(moving_average(main_array, window))

IndexError: tuple index out of range

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [172]:
window = np.arange(1,10)
window.shape[0]

9

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)