## Linear Algebra Quiz #2

![title](./img/2_1.jpeg)

We strongly suggest working with numpy :)

In [1]:
#Do your imports here
import numpy as np

![title](./img/2_2.png)
- Which vectors below define a plane spanned by a linear combination?

In [1]:
def plane(vec1, vec2, vec3):
    #returns false if the vectors don't define a plane and returns which are those vectors if true


    

def complete_plane(*inputs):
    pass    
    #returns the first set of vectors to complete a plane, false otherwise

IndentationError: expected an indented block (<ipython-input-1-2e7a2fba7dc3>, line 5)

![title](./img/2_3.png)
- What is the solution for a and b?

In [7]:
# do you need a function for this? What is the most efficient way to solve it?
# A_inv = np.linalg.inv([[2,3],[10,15]])
# B = np.array([[-1],[-5]])
# X = np.dot(A_inv, B)
# Above returns singular matrix error --> no unique solution (i.e. infinite or no solution)
A = np.array([[2,3],[10,15]])
B = np.array([[-1],[-5]])
print(np.linalg.lstsq(A, B))

(array([[-0.15384615],
       [-0.23076923]]), array([], dtype=float64), 1, array([1.83847763e+01, 1.97069097e-15]))
<ipython-input-7-2aa86b802808>:8: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  print(np.linalg.lstsq(A, B))


![title](./img/2_4.png)
- What is the solution for a and b?

In [6]:
# Idem. Do you need a function for this? What is the most efficient way to solve it?
# A_inv = np.linalg.inv([[-1,3],[-1,3]])
# B = np.array([[1],[5]])
# X = np.dot(A_inv, B)
# Above returns singular matrix error. Clearly above set of equations has no solution,
# but trying with numpy anyways
A = np.array([[-1,3],[-1,3]])
B = np.array([[1],[5]])
np.linalg.lstsq(A, B)

<ipython-input-6-63eeea4d30c9>:9: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A, B)


(array([[-0.3],
        [ 0.9]]),
 array([], dtype=float64),
 1,
 array([4.47213595, 0.        ]))