In [6]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [7]:
my_array = np.random.randint(1,10, size = (5,5))

print("Before swapping:\n ", my_array)
my_array[[0,3]] = my_array[[3,0]]
print("After swapping row 1 and row 4:\n ", my_array)

Before swapping:
  [[3 8 6 1 2]
 [9 3 9 9 7]
 [3 3 6 1 8]
 [7 7 8 4 8]
 [8 4 6 2 4]]
After swapping row 1 and row 4:
  [[7 7 8 4 8]
 [9 3 9 9 7]
 [3 3 6 1 8]
 [3 8 6 1 2]
 [8 4 6 2 4]]


**75. How to compute averages using a sliding window over an array?**

In [8]:
def moving_average(arr, window):
    """
    Inputs: 
    arr: 1D or 2D array
    window: window size over which to average
    Returns:
    Array with the averages
    """
    rows = arr.shape[0] - (window.shape[0] - 1)
    columns = arr.shape[1] - (window.shape[1] - 1)
    averages = np.zeros((rows, columns))

    for i in range(rows):
        for j in range(columns):
            averages[i, j] = np.mean(arr[i:i+1, j, j+1])/(rows*columns)
            
    return averages    

main_array = np.arange(1,10)
window = np.asarray([2,2])
print(moving_average(main_array, window))

IndexError: tuple index out of range